### PR TITLE
Minor fixes to the sh script

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by wellle** [comment]
Good stuff!

But `--no-run-if-empty` is not available for BSD xargs (like on Mac OS). Do you see a more portable way?

**Comment by blueyed** [comment]
But it has the short -r option for comparability? (http://www.freebsd.org/cgi/man.cgi?query=xargs)

**Comment by wellle** [comment]
Sounds good, lets use `-r` then.

**Comment by blueyed** [comment]
Amended the commit.

**Comment by wellle** [comment]
Actually no, unfortunately it still doesn't work.

1__root_storage-1____sh__and_add_click_time_ _8ad181c_ _adjust_android_sdk_and_graphite_browser

For reference, here's `man xargs` on my Mac, it doesn't have the `-r` either: https://gist.github.com/wellle/719a7fea9d3243bcce92

Sorry for all the back and fourth.

**Comment by blueyed** [comment]
Does it behave like with `-r` though?
What does `echo | xargs echo 1` say for you?

**Comment by wellle** [comment]
Yes that screenshot was with the `-r` version. It looked similar with `--no-run-if-empty`.

It prints nothing:
```
~: echo | xargs echo 1
~:
```

**Comment by blueyed** [comment]
Ok.  A workaround might be to use `-r` conditionally then, or test for the list before calling capturepane (what I've done now).

**Comment by wellle** [comment]
Yeah I think checking the list is the cleanest approach. Now you can remove the `-r` again.

**Comment by blueyed** [comment]
Yes, amended the commit(s).

**Comment by wellle** [comment]
Beautiful, thank you :+1:

**Pull request merged**
